---
  title: "Compose"
  description: "Documented Methods"
  sections: 
    - 
      type: "markdown-section"
      content: "compose\n\nCompose is a operator that enables you to run multiple operations on a DataModel all at once.\nThe resulting DataModel will be the result of all the operation provided. The operations provided\nwill be executed in a serial manner ie. result of one operation will be the input for the next\noperations.\n\nSuported operations in compose are\n- select\n- project\n- groupBy\n- bin\n- compose"
    - 
      type: "markdown-section"
      content: "<p class=\"sub-header\">Parameters:</p>\n<table><thead><tr><td>Name</td><td>Type</td><td>Description</td></tr></thead>\n<tr>\n                <td class=\"param-name\">operations</td>\n                <td><p>Array&lt;Operations&gt;</p> </td>\n                <td><p>: An array of operation that will be applied on the datatable.</p> </td>\n            </tr></table>"
    - 
      type: "code-section"
      content: "const data = [\n  { id: 1, netprofit: 100, netsales: 200, _first: 'Hello', _second: 'Jude' },\n  { id: 4, netprofit: 200, netsales: 250, _first: 'Bollo', _second: 'Wood' },\n];\nconst schema = [\n  { name: 'id', type: 'dimension' },\n  { name: 'netprofit', type: 'measure',defAggFn: 'avg' },\n  { name: 'netsales', type: 'measure' },\n  { name: '_first', type: 'dimension' },\n  { name: '_second', type: 'dimension'},\n  ];\n\nlet composedFn = compose(\n   select(fields => fields.netprofit.value <= 15),\n   project(['netprofit', 'netsales']));\n\nconst dataModel = new DataModel(data1, schema1);\n\nlet composedDm = composedFn(dataModel);\n\nThe composed DataModel will contain the result which might me obtained if the two\noperations were run seperately on datamodel."
      preamble: ""
    - 
      type: "markdown-section"
      content: "<a name=DataModel></a><p class=\"sub-header\">Returns:</p>\n\n <span style=\"font-family: 'Source Code Pro';\">DataModel:</span>"
    - 
      type: "markdown-section"
      content: "bin\n\nThis is compose bin operator.It performs the binning operation"
    - 
      type: "markdown-section"
      content: "<p class=\"sub-header\">Parameters:</p>\n<table><thead><tr><td>Name</td><td>Type</td><td>Description</td></tr></thead>\n<tr>\n                <td class=\"param-name\"></td>\n                <td><p>args</p> </td>\n                <td><p>See [DataModel} and [DataModel&#39;s bin function ]{@link DataModel#bin](DataModel} and [DataModel&#39;s bin function ]{@link DataModel#bin).</p> </td>\n            </tr></table>"
    - 
      type: "markdown-section"
      content: "select\n\nThis is compose select operator.It performs the select operation"
    - 
      type: "markdown-section"
      content: "<p class=\"sub-header\">Parameters:</p>\n<table><thead><tr><td>Name</td><td>Type</td><td>Description</td></tr></thead>\n<tr>\n                <td class=\"param-name\"></td>\n                <td><p>args</p> </td>\n                <td><p>See [DataModel} and [DataModel&#39;s select function ]{@link DataModel#select](DataModel} and [DataModel&#39;s select function ]{@link DataModel#select).</p> </td>\n            </tr></table>"
    - 
      type: "markdown-section"
      content: "project\n\nThis is compose project operator.It performs the project operations"
    - 
      type: "markdown-section"
      content: "<p class=\"sub-header\">Parameters:</p>\n<table><thead><tr><td>Name</td><td>Type</td><td>Description</td></tr></thead>\n<tr>\n                <td class=\"param-name\"></td>\n                <td><p>args</p> </td>\n                <td><p>See [DataModel} and [DataModel&#39;s project function ]{@link DataModel#project](DataModel} and [DataModel&#39;s project function ]{@link DataModel#project).</p> </td>\n            </tr></table>"
    - 
      type: "markdown-section"
      content: "groupBy\n\nThis is compose groupBy operator.It performs the groupBy operations"
    - 
      type: "markdown-section"
      content: "<p class=\"sub-header\">Parameters:</p>\n<table><thead><tr><td>Name</td><td>Type</td><td>Description</td></tr></thead>\n<tr>\n                <td class=\"param-name\"></td>\n                <td><p>args</p> </td>\n                <td><p>See [DataModel} and [DataModel&#39;s groupBy function ]{@link DataModel#groupBy](DataModel} and [DataModel&#39;s groupBy function ]{@link DataModel#groupBy).</p> </td>\n            </tr></table>"
